# Generated by Django 4.2.11 on 2025-04-02 10:34

import app_pottompatti.models
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eskuvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eskuvo_szoveg', django_quill.fields.QuillField(verbose_name='Esküvő szöveg')),
            ],
            options={
                'verbose_name': 'Esküvő szöveg',
                'verbose_name_plural': 'Esküvő szöveg',
            },
        ),
        migrations.CreateModel(
            name='Kapcsolat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nyitvatartas', models.CharField(max_length=50, verbose_name='nyitvatartás')),
                ('emailcim', models.CharField(default='', max_length=50, verbose_name='email cím')),
                ('adress', models.CharField(default='', max_length=50, verbose_name='cím')),
                ('adresslink', models.CharField(default='', max_length=50, verbose_name='google térkép link')),
                ('facebook', models.CharField(default='', max_length=100, verbose_name='facebook link')),
                ('instagram', models.CharField(default='', max_length=100, verbose_name='instagram link')),
                ('tiktok', models.CharField(default='', max_length=100, verbose_name='tiktok link')),
                ('telefonszam', models.CharField(default='', max_length=50, verbose_name='telefonszám')),
            ],
            options={
                'verbose_name': 'Kapcsolati adatok',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_main_category', models.CharField(choices=[('tortak', 'Torták'), ('sutemenyek', 'Sütemények')], default='tortak', max_length=10, verbose_name='főkategória')),
                ('name', models.CharField(max_length=200, verbose_name='termék kategória')),
            ],
            options={
                'verbose_name': 'kategória',
                'verbose_name_plural': 'kategóriák',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='termek', max_length=200, verbose_name='név')),
                ('description', models.TextField(default='leírás később érkezik', max_length=300, verbose_name='termék leírás')),
                ('photo', models.ImageField(default='/app_pottompatti/img/bakery.jpg', upload_to='app_pottompatti/img/photos/', verbose_name='kép')),
                ('photo_tumb', models.ImageField(editable=False, upload_to='app_pottompatti/img/thumbs/')),
                ('permanent', models.BooleanField(default=True, verbose_name='állandó kínálat')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pottompatti.productcategory', verbose_name='kategória')),
            ],
            options={
                'verbose_name': 'termék',
                'verbose_name_plural': 'termékek',
            },
            bases=(app_pottompatti.models.ImageHandlerMixin, models.Model),
        ),
    ]
