# Generated by Django 5.0.3 on 2024-04-03 13:08

import django.core.validators
import django.db.models.deletion
import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bemutatkozas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    django_quill.fields.QuillField(verbose_name="Bemutatkozó szöveg"),
                ),
            ],
            options={
                "verbose_name": "Bemutatkozás",
                "verbose_name_plural": "Bemutatkozás",
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="név")),
                (
                    "priority",
                    models.IntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MaxValueValidator(10),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="sorrend",
                    ),
                ),
                (
                    "category_cover",
                    models.ImageField(
                        default="app_pottompatti/img/",
                        upload_to="app_brandon_photography/img/thumbs",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductMainCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="név")),
                (
                    "priority",
                    models.IntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MaxValueValidator(10),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="sorrend",
                    ),
                ),
                (
                    "category_cover",
                    models.ImageField(
                        default="app_pottompatti/img/",
                        upload_to="app_brandon_photography/img/thumbs",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="app_pottompatti/img/photos/",
                        verbose_name="kiemelt kép",
                    ),
                ),
                (
                    "photo_tumb",
                    models.ImageField(
                        editable=False, upload_to="app_menhely/img/thumbs/"
                    ),
                ),
                (
                    "product_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_pottompatti.productcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "kiemelt kép",
                "verbose_name_plural": "kiemelt képek",
            },
        ),
        migrations.AddField(
            model_name="productcategory",
            name="product_main_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app_pottompatti.productmaincategory",
            ),
        ),
    ]
