# Generated by Django 5.0.3 on 2024-04-05 13:35

import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_pottompatti", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TerjBeHozzank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    django_quill.fields.QuillField(verbose_name="Bemutatkozó szöveg"),
                ),
            ],
            options={
                "verbose_name": "Térj Be Hozzánk Szöveg",
                "verbose_name_plural": "Térj Be Hozzánk Szöveg",
            },
        ),
    ]
