# Generated by Django 4.2.11 on 2025-04-02 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pottompatti', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kapcsolat',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='kapcsolat',
            old_name='adresslink',
            new_name='addresslink',
        ),
    ]
