# Generated by Django 4.2.11 on 2025-04-14 10:08

import app_pottompatti.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pottompatti', '0002_rename_adress_kapcsolat_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TortaKepek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='/app_pottompatti/img/bakery.jpg', upload_to='app_pottompatti/img/photos/', verbose_name='kép')),
                ('photo_tumb', models.ImageField(editable=False, upload_to='app_pottompatti/img/thumbs/')),
            ],
            options={
                'verbose_name': 'kép',
                'verbose_name_plural': 'képek',
            },
            bases=(app_pottompatti.models.ImageHandlerMixin, models.Model),
        ),
    ]
