# Generated by Django 5.0.3 on 2024-04-08 20:14

import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pottompatti', '0002_terjbehozzank'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllasLehetoseg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_quill.fields.QuillField(verbose_name='Álláslehetőség')),
            ],
            options={
                'verbose_name': 'Álláslehetőség',
                'verbose_name_plural': 'Álláslehetőségek',
            },
        ),
        migrations.CreateModel(
            name='Kapcsolat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nyitvatartas', models.CharField(max_length=50, verbose_name='nyitvatartás')),
                ('emailcim', models.CharField(default='', max_length=50, verbose_name='email cím')),
                ('adress', models.CharField(default='', max_length=50, verbose_name='cím')),
                ('adresslink', models.CharField(default='', max_length=50, verbose_name='google térkép link')),
                ('facebook', models.CharField(default='', max_length=50, verbose_name='facebook link')),
                ('telefonszam', models.CharField(default='', max_length=50, verbose_name='telefonszám')),
            ],
            options={
                'verbose_name': 'Kapcsolat',
                'verbose_name_plural': 'Kapcsolat',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'termék', 'verbose_name_plural': 'termékek'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'termék alkategória', 'verbose_name_plural': 'termék alkategóriák'},
        ),
        migrations.AlterModelOptions(
            name='productmaincategory',
            options={'verbose_name': 'termék főkategória', 'verbose_name_plural': 'termék főkategóriák'},
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='leírás később érkezik', max_length=300, verbose_name='termék leírás'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='app_pottompatti/img/photos/', verbose_name='kép'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_tumb',
            field=models.ImageField(editable=False, upload_to='app_pottompatti/img/thumbs/'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category_cover',
            field=models.ImageField(default='app_pottompatti/img/', upload_to='app_pottompatti/img/thumbs'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=200, verbose_name='termék kategória'),
        ),
        migrations.AlterField(
            model_name='productmaincategory',
            name='category_cover',
            field=models.ImageField(default='app_pottompatti/img/', upload_to='app_pottompatti/img/thumbs'),
        ),
        migrations.AlterField(
            model_name='productmaincategory',
            name='name',
            field=models.CharField(max_length=200, verbose_name='termék fő kategória'),
        ),
    ]
