# Generated by Django 4.2.11 on 2024-04-09 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pottompatti', '0004_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='category_cover',
        ),
    ]
