# Generated by Django 4.2.11 on 2024-04-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pottompatti', '0006_remove_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='termek', max_length=200, verbose_name='név'),
        ),
    ]
