# Generated by Django 4.2.11 on 2024-04-16 21:31

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_pottompatti', '0008_product_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hirek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Hír cím')),
                ('content', django_quill.fields.QuillField(verbose_name='Hír szövege')),
                ('photo', models.ImageField(default='/app_pottompatti/img/bakery.jpg', upload_to='app_pottompatti/img/photos/', verbose_name='kép')),
                ('photo_tumb', models.ImageField(editable=False, upload_to='app_pottompatti/img/thumbs/')),
            ],
            options={
                'verbose_name': 'Hír',
                'verbose_name_plural': 'Hírek',
            },
        ),
        migrations.DeleteModel(
            name='Bemutatkozas',
        ),
    ]
