# Generated by Django 4.2.11 on 2024-04-17 14:02

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):
    dependencies = [
        ("app_pottompatti", "0009_hirek_delete_bemutatkozas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hirek",
            name="content",
            field=django_quill.fields.QuillField(
                max_length=200, verbose_name="Hír szövege"
            ),
        ),
        migrations.AlterField(
            model_name="terjbehozzank",
            name="content",
            field=django_quill.fields.QuillField(
                max_length=200, verbose_name="Bemutatkozó szöveg"
            ),
        ),
    ]
