# Generated by Django 4.2.11 on 2024-04-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pottompatti', '0012_alter_hirek_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='kapcsolat',
            name='instagramlink',
            field=models.CharField(default='', max_length=50, verbose_name='tiktok link'),
        ),
        migrations.AddField(
            model_name='kapcsolat',
            name='tiktoklink',
            field=models.CharField(default='', max_length=50, verbose_name='tiktok link'),
        ),
    ]
