# Generated by Django 4.2.11 on 2024-10-19 18:18

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_pottompatti', '0013_kapcsolat_instagramlink_kapcsolat_tiktoklink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eskuvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eskuvo_szoveg', django_quill.fields.QuillField(verbose_name='Esküvő szöveg')),
            ],
            options={
                'verbose_name': 'Esküvő szöveg',
                'verbose_name_plural': 'Esküvő szövegek',
            },
        ),
        migrations.CreateModel(
            name='EskuvoKerdezzFelelek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eskuvo_kerdes', models.TextField(default='', max_length=300, verbose_name='kérdés')),
                ('eskuvo_valasz', models.TextField(default='', max_length=300, verbose_name='válasz')),
            ],
            options={
                'verbose_name': 'Esküvő kérdezz felelek',
                'verbose_name_plural': 'Esküvő kérdezz felelek objektumok',
            },
        ),
        migrations.RemoveField(
            model_name='kapcsolat',
            name='instagramlink',
        ),
        migrations.RemoveField(
            model_name='kapcsolat',
            name='tiktoklink',
        ),
    ]
