# Generated by Django 4.2.11 on 2024-10-19 20:03

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_pottompatti', '0014_eskuvo_eskuvokerdezzfelelek_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rendezveny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eskuvo_szoveg', django_quill.fields.QuillField(verbose_name='Rendezvény szöveg')),
            ],
            options={
                'verbose_name': 'Rendezvény szöveg',
                'verbose_name_plural': 'Rendezvény szöveg',
            },
        ),
        migrations.CreateModel(
            name='RendezvenyKerdezzFelelek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rendezveny_kerdes', models.TextField(default='', max_length=300, verbose_name='kérdés')),
                ('rendezveny_valasz', models.TextField(default='', max_length=300, verbose_name='válasz')),
            ],
            options={
                'verbose_name': 'Rendezvény kérdezz felelek',
                'verbose_name_plural': 'Rendezvény kérdezz felelek objektumok',
            },
        ),
        migrations.AlterModelOptions(
            name='eskuvo',
            options={'verbose_name': 'Esküvő szöveg', 'verbose_name_plural': 'Esküvő szöveg'},
        ),
    ]
