# Generated by Django 4.2.11 on 2024-10-19 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pottompatti', '0015_rendezveny_rendezvenykerdezzfelelek_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rendezveny',
            old_name='eskuvo_szoveg',
            new_name='rendezveny_szoveg',
        ),
    ]
