# Generated by Django 4.2.11 on 2024-10-19 20:59

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_pottompatti', '0016_rename_eskuvo_szoveg_rendezveny_rendezveny_szoveg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('karrier', django_quill.fields.QuillField(verbose_name='Karrier szöveg')),
            ],
            options={
                'verbose_name': 'Karrier szöveg',
                'verbose_name_plural': 'Karrier szöveg',
            },
        ),
    ]
